fixtures:
  repositories:
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    provision: 'git://github.com/puppetlabs/provision.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
  symlinks:
    registry: "#{source_dir}"
    mixed_default_settings: "#{source_dir}/spec/fixtures/mixed_default_settings"
