---
.travis.yml:
  script: "\"bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--color --format documentation'\""
  extras:
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="3.3.0"
  # The allow_failures section should not be here
  # Only exists as part of modsync update for puppet branding
  allow_failures:
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 4.0"
Gemfile:
  supports_windows: true
  required:
    ':development':
      - gem: rake
      - gem: rspec
        version: '~>2.14.1'
      - gem: puppet-lint
      - gem: puppetlabs_spec_helper
        version: '~>0.10.3'
      - gem: puppet_facts
      - gem: mocha
        version: '~>0.10.5'
    ':system_tests':
      - gem: beaker
      - gem: beaker-puppet_install_helper
Rakefile:
  unmanaged: true
spec/spec_helper.rb:
  unmanaged: true
appveyor.yml:
  matrix_extras:
    - PUPPET_GEM_VERSION: 3.3.0
      RUBY_VER: 193
  test_script:
    - 'bundle exec rspec spec/unit -fd -b'
MAINTAINERS.md:
  maintainers:
    - "Puppet Windows Team `windows |at| puppet |dot| com`"
NOTICE:
  copyright_holders:
    - name: 'Puppet, Inc.'
      begin: 2012
      end: 'latest'